FROM mysql:8.0.31
LABEL maintainer="jujin1324@daum.net"
LABEL dockerhub="https://hub.docker.com/_/mysql"

ADD mysql-starter.cnf /etc/mysql/conf.d/
ENV MYSQL_ROOT_PASSWORD root
ENV MYSQL_DATABASE mysql_starter
ENV MYSQL_USER starter
ENV MYSQL_PASSWORD mysql
